apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications-bootstrap
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators: 
          - list:
              elements:
                - cluster: cluster1
                  environment: dev
                - cluster: cluster1
                  environment: staging
                # - cluster: cluster2
                #   environment: pro
          - git:
              repoURL: https://github.com/davidseve/gitops-repository.git
              revision: HEAD
              files:
              - path: apps/**/{{.cluster}}/{{.environment}}/chart-config.json
              pathParamPrefix: app         
  template:
    metadata:
      name: '{{.cluster}}-{{.environment}}-{{index .app.path.segments 1}}'
    spec:
      project: default
      sources:
      - path: '{{.chartPath}}'
        repoURL: '{{.repoURL}}'
        targetRevision: '{{.targetRevision}}'
        helm:
          valueFiles:
            - $values/apps/{{index .app.path.segments 1}}/base/values.yaml            
            - $values/apps/{{index .app.path.segments 1}}/{{.cluster}}/values.yaml
            - $values/apps/{{index .app.path.segments 1}}/{{.cluster}}/{{.environment}}/values.yaml      
            - $values/clusters/{{.cluster}}/values.yaml
            - $values/clusters/{{.cluster}}/{{.environment}}/values.yaml        
      - ref: values
        repoURL: 'https://github.com/davidseve/gitops-repository.git'
        targetRevision: HEAD
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.environment}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
