
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps1
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: cluster1
            environment: dev
          # - cluster: cluster1
          #   environment: staging
          # - cluster: cluster1
          #   environment: prod
          # - cluster: cluster2
          #   environment: dev
          # - cluster: cluster2
          #   environment: staging
          # - cluster: cluster2
          #   environment: prod
  template:
    metadata:
      name: '{{cluster}}-{{environment}}-app1'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/davidseve/gitops-repository'
        targetRevision: HEAD
        path: apps/app1/base
        helm:
          valueFiles:
            - values.yaml
            - ../../{{cluster}}/values.yaml
            - ../../{{cluster}}/{{environment}}/values.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{environment}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true